#!/bin/bash

set -e

function clean_up {
    echo "====== Cleaning up ======"

    if [[ -d "$DOWNLOAD_DIR" ]]
    then
        rm -rf "$DOWNLOAD_DIR"
    fi
}
trap clean_up EXIT SIGINT SIGTERM

print_the_pkgname_part_from_srpm_filename_path() {
	local srpm_file=$1

	fnmpart=$(echo $srpm_file | sed -e "s/.*\///")
	fnm_ext_removed=$(echo $fnmpart | sed -e "s/\(.*\)\.src\.rpm/\1/")

	#print the name part of the package from file name
	#which requires us to print all the parts of the file name except for the
	#last two parts, where the parts have been derived using hyphen ("-") as 
	#the field separator
	echo $fnm_ext_removed | awk '
		BEGIN {FS = "-"} 
		NF < 3 {printf $0} 
		NF >= 3 { 
			for (i = 1; i <= NF - 2; i++)
			{ 
				if (i > 1) 
				{
					printf "-"
				} 
				printf $i; 
			}
		}'
}

print_the_pkgver_part_from_srpm_filename_path() {
	local srpm_file=$1

	fnmpart=$(echo $srpm_file | sed -e "s/.*\///")
	fnm_ext_removed=$(echo $fnmpart | sed -e "s/\(.*\)\.src\.rpm/\1/")

	#print the version part of the package from file name
	#which requires us to print the second last part of the file name, where
	#the parts have been derived using hyphen ("-") as the field separator
	echo $fnm_ext_removed | awk '
		BEGIN {FS = "-"} 
		NF < 3 {printf $0} 
		NF >= 3 {print $(NF - 1)}
		'
}

update_cgmanifest() {
    local import_srpm_dir=$1
    local cgmjson_fl=$2
    local srpms

    WORKING_CGM_FILE="$(mktemp -q)"

    srpms=$(find "$import_srpm_dir" -type f -name '*.src.rpm')$
    for srpm_file in $srpms; do
        echo $srpm_file
	pkgnm=$(print_the_pkgname_part_from_srpm_filename_path $srpm_file)
	echo $pkgnm

	pkgver=$(print_the_pkgver_part_from_srpm_filename_path $srpm_file)
	echo $pkgver

	#Carry out the substitution of the version field in the manifest json file for the given package
	awk -v awkvar_pkgnm="$pkgnm" -v awkvar_pkgver="$pkgver" -v awkvar_nmregex="\"name\": \"$pkgnm\"" -v awkvar_verregex="\"version\":" '
	BEGIN { changeverflag = 0 }
	# The line containing the name of the package must be printed as is, and lead to a flag set that ensures that
	# the next version line is changed, because that is the version line corresponding to this package
	$0 ~ awkvar_nmregex { changeverflag = 1
				print $0 
			}
	# The version line must have the determined version mentioned in it if it corresponds to the given package, i.e. the changeverflag is set
	# Any other version line must be printed as is
	$0 ~ awkvar_verregex {
			if (changeverflag == 1)
			{
				printf ("          \"version\": \"%s\",\n", awkvar_pkgver)
				changeverflag = 0
			}
			else
			{
				print $0
			}
		}
	# All the lines except for the ones that match the above criteria, must be printed unchanged.
	        {
	                if (! ($0 ~ awkvar_nmregex) && !($0 ~ awkvar_verregex) )
			{
				print $0
			}
		}
	' $cgmjson_fl > $WORKING_CGM_FILE
	
	cp $WORKING_CGM_FILE $cgmjson_fl
	
	done


}

expand_srpms() {
    local import_srpm_dir=$1
    local build_spec_dir=$2
    local logs_dir=$3
    local tools_dir
    local srpms

    tools_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

    srpms=$(find "$import_srpm_dir" -type f -name '*.src.rpm')

    for srpm_file in $srpms; do
        spec_name=$(rpm -qp "$srpm_file" --define='with_check 1' --queryformat '%{NAME}/%{NAME}.spec' 2>/dev/null)
        spec_destination=$build_spec_dir/$spec_name
        spec_dir=$(dirname "$spec_destination")
        srpm_log="$logs_dir/$spec_name.log"
        srpm_log_dir=$(dirname "$srpm_log")

        mkdir -p "$spec_dir"
        mkdir -p "$srpm_log_dir"

        echo "Extracting $spec_destination"
        cd "$spec_dir" && rpm2cpio "$srpm_file" | cpio -idvu &>"$srpm_log" || echo "Failed to expand $srpm_file"

#        if ! "$tools_dir/sanitize_specs/sanitize_specs.sh" "$spec_destination"
#        then
#            found_errors=1
#        fi
    done

    if [[ -n $found_errors ]]
    then
        echo "WARNING: finished with errors, check logs above." >&2
    fi
}

print_usage() {
    echo "Usage:"
    echo "import-specs.sh [distro] [package list file] [cgmanigest json file] [directory path if srpms to be retained]"
    echo
    echo "Supported distros: fedora, centos, opensuse"
    echo
    echo "Example for not retaining srpms"
    echo "import-specs.sh fedora /path/to/packagelist.txt cgmanifest.json"
    echo "or"
    echo "Example for retaining srpms"
    echo "import-specs.sh fedora /path/to/packagelist.txt cgmanifest.json dir_to_retain_srpms"
    echo "Caution: the cgmanifest json file provided as input is overwritten by the contents generated by this script"
    exit
}

if [ $# -lt 3 ]; then
    print_usage
fi

DISTRO=$1
PACKAGE_LIST=$2
CGM_JSON_FILE=$3

if [ $# -eq 4 ]
then
retain_srpm_flag=1
RETAIN_SRPM_DIR=$4
else
retain_srpm_flag=0
fi

SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/output/$DISTRO"
LOGS_DIR="$OUTPUT_DIR/logs"
SPECS_DIR="$OUTPUT_DIR/specs"
IMAGE_TAG="$DISTRO-srpm-importer"

DOWNLOAD_DIR="$(mktemp -d)"

mkdir -p "$LOGS_DIR"
mkdir -p "$SPECS_DIR"


cp "$PACKAGE_LIST" "$DOWNLOAD_DIR/packagelist.txt"

echo "====== Preparing Docker image ======"
docker build -t "$IMAGE_TAG" -f "$SCRIPT_DIR/container/$DISTRO.Dockerfile" "$SCRIPT_DIR/container"

echo "====== Retrieving source RPMs ======"
docker run -v "$DOWNLOAD_DIR":/srpms --rm "$IMAGE_TAG"

if [ $retain_srpm_flag -eq 1 ]
then
cp -r $DOWNLOAD_DIR $RETAIN_SRPM_DIR
fi

echo "====== Updating cgmanifest file provided ======"
update_cgmanifest "$DOWNLOAD_DIR" "$CGM_JSON_FILE"

echo "cgmanifest file updated"

echo "====== Expanding retrieved source RPMs ======"
expand_srpms "$DOWNLOAD_DIR" "$SPECS_DIR" "$LOGS_DIR"

echo "SPECs written to $SPECS_DIR"
