#!/usr/bin/bash
# First argument has to be the state for which you intend to carry out the search
# Second argument has to be the list of authornames file

print_usage() {
	echo "Usage:"
	echo "$0 state_of_PR fullpathto_file_listing_author_github_names path_to_gitrepodir"
	echo "	state_of_PR {open|closed|merged|unmerged|all}"
	exit 1
}

if [ $# -ne 3 ]
then
	print_usage
fi

state=$1
listauthors=$2
gitrepopath=$3
search_template="EMPTY"

case "$state" in 
	open ) ;;
	closed ) ;;
	merged ) ;;
	all ) ;;
	unmerged ) search_template='is:closed is:unmerged';;
	* ) echo "Invalid state specified=$state"; print_usage;;
esac

#set -x
pushd $gitrepopath > /dev/null
for githubname in `cat $listauthors`
do
echo
echo "========================================================================="
echo "$githubname"::"$state"
echo "========================================================================="
if [  "$search_template" == "EMPTY" ]
then
	#echo "1" $search_template
	gh pr list -L 100 --author "$githubname" --state $state
else
	#echo "2" $search_template
	gh pr list -L 100 --author "$githubname" -S "$search_template"
fi
done
popd > /dev/null
