#./pkgbld.sh -s ../SPECS-EXTENDED -p "CharLS"
echo
echo
echo "Building 1 to 100 packages================================"
./pkgbld.sh -s ../SPECS-EXTENDED -p "389-ds-base  CharLS  GConf2  GeoIP  GeoIP-GeoLite-data  Judy  LibRaw  ORBit2  OpenEXR  PEGTL  PyGreSQL  SDL  SDL2  SDL_sound  SuperLU  Xaw3d  a52dec  accountsservice  acpid  adcli  adobe-mappings-cmap  adobe-mappings-pdf  advancecomp  alsa-firmware  alsa-plugins  amtk  amtterm  ansible-freeipa  aopalliance  apache-commons-beanutils  apache-commons-codec  apache-commons-collections  apache-commons-collections4  apache-commons-compress  apache-commons-daemon  apache-commons-dbcp  apache-commons-digester  apache-commons-httpclient  apache-commons-io  apache-commons-jexl  apache-commons-lang  apache-commons-net  apache-commons-pool  apache-commons-pool2  apache-commons-validator  apache-commons-vfs2  apache-parent  argparse-manpage  args4j  arptables  arpwatch  asio  aspell-en  audiofile  babeltrace  babl  baekmuk-ttf-fonts  base64coder  bats  bcache-tools  bcel  bea-stax  beust-jcommander  biosdevname  blosc  bogofilter  bolt  boom-boot  booth  botan2  breezy  bsf  buildah  bwidget  cachefilesd  cairomm  capnproto  capstone  cassandra  catatonit  catch1  cdparanoia  cdrdao  celt051  certmonger  cfitsio  cgdcbxd  cglib  chan  cim-schema  cjkuni-uming-fonts  cjose  cldr-emoji-annotation  clucene  clutter  clutter-gst3  clutter-gtk  cmake-fedora  cogl  colorize"
echo
echo
echo "Building 101 to 200 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "compat-lua  console-setup  container-exception-logger  containernetworking-plugins  convmv  corosync  corosync-qdevice  cpp-hocon  cppcheck  cpptest  cpuid  crash-ptdump-command  cri-o  criu  crypto-policies  cscope  custodia  dbus-c++  dbxtool  dcraw  deltarpm  delve  device-mapper-persistent-data  diffstat  discount  dleyna-connector-dbus  dleyna-core  dmraid  docbook-simple  docbook-slides  docbook-style-dsssl  docbook-utils  docbook2X  docbook5-style-xsl  dogtail  dotconf  dovecot  dpkg  driverctl  dropwatch  drpm  dumpet  dvd+rw-tools  dyninst  ecj  edac-utils  efax  efi-rpm-macros  elinks  enca  enchant  enscript  evemu  exempi  exiv2  fabtests  facter  fakechroot  fapolicyd  fdk-aac-free  fence-virt  fetchmail  fftw  filebench  fipscheck  flac  flite  fltk  fonts-rpm-macros  foomatic-db  freeradius  freexl  fros  fstrm  fuse-overlayfs  fuse-sshfs  fxload  gavl  gconf-editor  gcr  gdal  gdisk  generic-logos  genwqe-tools  geoclue2  geolite2  geronimo-specs  ghc-srpm-macros  gl-manpages  glassfish-annotation-api  glew  glm  glog  gnome-desktop-testing  gnome-doc-utils  gnome-icon-theme  gnome-keyring  gnu-getopt  gnu-regexp  go-rpm-macros"
echo
echo
echo "Building 201 to 300 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "gom  google-api-python-client  google-crosextra-caladea-fonts  google-crosextra-carlito-fonts  google-noto-cjk-fonts  google-noto-emoji-fonts  gphoto2  gpm  gpsbabel  graphene  graphite2  gsl  gspell  gssdp  gssntlmssp  gstreamer1  gstreamer1-plugins-base  gtk-vnc  gtkspell  guava20  gupnp  gupnp-av  gupnp-dlna  gupnp-igd  hawtjni-runtime  hdf  hiera  highlight  hping3  hsakmt  httpcomponents-core  hunspell-af  hunspell-ar  hunspell-as  hunspell-ast  hunspell-az  hunspell-be  hunspell-bg  hunspell-bn  hunspell-br  hunspell-ca  hunspell-cop  hunspell-csb  hunspell-cv  hunspell-cy  hunspell-da  hunspell-de  hunspell-dsb  hunspell-el  hunspell-eo  hunspell-es  hunspell-et  hunspell-eu  hunspell-fa  hunspell-fj  hunspell-fo  hunspell-fr  hunspell-fur  hunspell-fy  hunspell-ga  hunspell-gd  hunspell-gl  hunspell-grc  hunspell-gu  hunspell-gv  hunspell-haw  hunspell-hi  hunspell-hil  hunspell-hr  hunspell-hsb  hunspell-ht  hunspell-hu  hunspell-hy  hunspell-ia  hunspell-id  hunspell-is  hunspell-it  hunspell-kk  hunspell-km  hunspell-kn  hunspell-ko  hunspell-ku  hunspell-ky  hunspell-la  hunspell-lb  hunspell-ln  hunspell-mai  hunspell-mg  hunspell-mi  hunspell-mk  hunspell-ml  hunspell-mn  hunspell-mos  hunspell-mr  hunspell-ms  hunspell-mt  hunspell-nds  hunspell-ne  hunspell-nl  hunspell-no"
echo
echo
echo "Building 301 to 400 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "hunspell-nr  hunspell-nso  hunspell-ny  hunspell-om  hunspell-or  hunspell-pa  hunspell-pl  hunspell-pt  hunspell-quh  hunspell-ro  hunspell-ru  hunspell-rw  hunspell-se  hunspell-shs  hunspell-si  hunspell-sk  hunspell-sl  hunspell-smj  hunspell-so  hunspell-sq  hunspell-sr  hunspell-sv  hunspell-sw  hunspell-ta  hunspell-te  hunspell-tet  hunspell-th  hunspell-tk  hunspell-tl  hunspell-tn  hunspell-tpi  hunspell-ts  hunspell-uk  hunspell-uz  hunspell-ve  hunspell-vi  hunspell-wa  hunspell-xh  hunspell-yi  hyphen  hyphen-as  hyphen-bg  hyphen-bn  hyphen-ca  hyphen-da  hyphen-de  hyphen-el  hyphen-es  hyphen-fa  hyphen-fo  hyphen-fr  hyphen-ga  hyphen-gl  hyphen-grc  hyphen-gu  hyphen-hi  hyphen-hsb  hyphen-hu  hyphen-ia  hyphen-id  hyphen-is  hyphen-it  hyphen-kn  hyphen-ku  hyphen-lt  hyphen-mi  hyphen-ml  hyphen-mn  hyphen-mr  hyphen-nl  hyphen-or  hyphen-pa  hyphen-pl  hyphen-pt  hyphen-ro  hyphen-ru  hyphen-sa  hyphen-sk  hyphen-sl  hyphen-sv  hyphen-ta  hyphen-te  hyphen-tk  hyphen-uk  ibus  ibus-chewing  ibus-hangul  ibus-kkc  ibus-libzhuyin  ibus-m17n  ibus-rawcode  ibus-sayura  ibus-table  ibus-table-chinese  icc-profiles-openicc  icon-naming-utils  iftop  iio-sensor-proxy  ilmbase  imaptest"
echo
echo
echo "Building 401 to 500 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "indent  intel-cmt-cat  ioping  ipa-pgothic-fonts  ipcalc  iprutils  iptstate  irssi  iso-codes  isomd5sum  iwd  jabberpy  jakarta-taglibs-standard  jansi  jarjar  javacc  jbigkit  jboss-interceptors-1.2-api  jdepend  jdom2  jfsutils  jimtcl  jlex  jline  jose  js-jquery  jsch  jsoncpp  jsoup  jtidy  junitperf  jzlib  kde-filesystem  kernel-rt  keybinder3  keycloak-httpd-client-install  kronosnet  kyotocabinet  ladspa  lame  langtable  lasso  latencytop  lcov  leatherman  ledmon  lensfun  lftp  libEMF  libIDL  libXScrnSaver  libabw  libao  libappstream-glib  libart_lgpl  libasyncns  libavc1394  libblockdev  libbsd  libbytesize  libcanberra  libcdio  libcdio-paranoia  libcdr  libchewing  libcli  libcmis  libcmpiutil  libcroco  libdap  libdatrie  libdazzle  libdbi  libdbi-drivers  libdbusmenu  libdc1394  libdeflate  libdmx  libdvdnav  libdvdread  libeasyfc  libecap  libecb  libeot  libepubgen  libesmtp  libetonyek  libexttextcat  libfreehand  libftdi  libgadu  libgdither  libgee  libgee06  libgeotiff  libgexiv2  libgit2-glib  libglade2  libgovirt  libgphoto2"
echo
echo
echo "Building 501 to 600 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "libgsf  libgta  libgxps  libhangul  libibcommon  libicns  libid3tag  libiec61883  libieee1284  libimobiledevice  libindicator  libiodbc  libipt  libiptcdata  libjcat  libkeepalive  libkkc  libkkc-data  libkml  liblangtag  libldb  liblerc  liblockfile  liblouis  liblqr-1  libmad  libmediaart  libmikmod  libmodman  libmodplug  libmodulemd1  libmpcdec  libmspub  libmtp  libmusicbrainz5  libmwaw  libnet  libntlm  libnumbertext  liboauth  libodfgen  libofa  libogg  liboggz  liboil  libomxil-bellagio  libopenraw  liboping  libosinfo  libotf  libotr  libpagemaker  libpaper  libpeas  libpfm  libpinyin  libplist  libpmemobj-cpp  libpng12  libpng15  libproxy  libqb  libqxp  librabbitmq  libraqm  libraw1394  libreport  librevenge  librx  libsamplerate  libsass  libsecret  libsigc++20  libsigsegv  libsmbios  libspiro  libsrtp  libstaroffice  libstemmer  libtdb  libteam  libtevent  libthai  libtheora  libtnc  libtomcrypt  libtommath  libtranslit  libucil  libunicap  libuninameslist  libusbmuxd  libutempter  libvarlink  libvdpau  libverto  libvisio  libvisual  libvorbis  libvpx"
echo
echo
echo "Building 601 to 700 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "libwnck3  libwpd  libwpe  libwpg  libwps  libwvstreams  libxklavier  libxmlb  libyami  libyubikey  libzmf  lilv  linuxconsoletools  lksctp-tools  lockdev  logwatch  lpsolve  lrzsz  lua-expat  lua-filesystem  lua-json  lua-lpeg  lua-lunit  lua-term  luksmeta  lv2  lzip  m17n-db  m17n-lib  mailx  mallard-rng  man-pages-cs  man-pages-es  man-pages-it  man-pages-ja  man-pages-ko  man-pages-pl  man-pages-ru  man-pages-zh-CN  mariadb-connector-odbc  marisa  maven-parent  mcelog  mdds  meanwhile  mecab  mecab-ipadic  media-player-info  memkind  metis  microcode_ctl  microdnf  minicom  minizip  mksh  mobile-broadband-provider-info  mod_auth_gssapi  mod_auth_mellon  mod_auth_openidc  mod_authnz_pam  mod_fcgid  mod_http2  mod_intercept_form_submit  mod_lookup_identity  mod_md  mod_security  mod_security_crs  mod_wsgi  mosh  mpage  mrtg  mt-st  mtx  mutt  mythes  mythes-bg  mythes-ca  mythes-cs  mythes-da  mythes-de  mythes-el  mythes-en  mythes-eo  mythes-es  mythes-fr  mythes-ga  mythes-hu  mythes-mi  mythes-ne  mythes-nl  mythes-pl  mythes-pt  mythes-ro  mythes-ru  mythes-sk  mythes-sl  mythes-sv  mythes-uk  neon  netcdf"
echo
echo
echo "Building 701 to 800 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "netcf  netlabel_tools  netpbm  netsniff-ng  nilfs-utils  nkf  nload  nodejs-nodemon  nodejs-packaging  nss-pam-ldapd  numatop  nvmetcli  objectweb-anttask  objenesis  ocaml-calendar  ocaml-camlp5  ocaml-csv  ocaml-curses  ocaml-extlib  ocaml-fpath  ocaml-libvirt  ocaml-markup  ocaml-tyxml  ocaml-xml-light  ocaml-zarith  ocl-icd  oddjob  ogdi  omping  opal  opencc  opencl-filesystem  opencl-headers  opencryptoki  opendnssec  openjade  openjpeg2  openobex  openoffice-lv  openrdate  openslp  openssl-ibmpkcs11  openwsman  optipng  opus  opusfile  orc  oro  os-prober  osgi-annotation  osgi-compendium  osgi-core  osinfo-db  osinfo-db-tools  overpass-fonts  pacemaker  pacrunner  pakchois  papi  paps  parallel  pbzip2  pcp  perl-Algorithm-Diff  perl-Alien-Build  perl-Alien-pkgconf  perl-AnyEvent  perl-AnyEvent-AIO  perl-AnyEvent-BDB  perl-App-FatPacker  perl-AppConfig  perl-Archive-Extract  perl-Authen-SASL  perl-B-Debug  perl-B-Hooks-EndOfScope  perl-B-Keywords  perl-B-Lint  perl-BDB  perl-BSD-Resource  perl-Browser-Open  perl-Business-ISBN  perl-Business-ISBN-Data  perl-CBOR-XS  perl-CSS-Tiny  perl-Class-Accessor  perl-Class-C3  perl-Class-C3-XS  perl-Class-Data-Inheritable  perl-Class-Factory-Util  perl-Class-Inspector  perl-Class-Load  perl-Class-Load-XS  perl-Class-Method-Modifiers  perl-Class-Singleton  perl-Class-Tiny  perl-Color-ANSI-Util  perl-Color-RGB-Util  perl-ColorThemeBase-Static  perl-ColorThemeRole-ANSI  perl-ColorThemeUtil-ANSI"
echo
echo
echo "Building 801 to 900 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "perl-ColorThemes-Standard  perl-Compress-LZF  perl-Compress-Raw-Lzma  perl-Config-AutoConf  perl-Config-INI  perl-Config-INI-Reader-Multiline  perl-Config-IniFiles  perl-Config-Simple  perl-Config-Tiny  perl-Const-Fast  perl-Convert-ASN1  perl-Convert-Bencode  perl-Coro  perl-Coro-Multicore  perl-Cpanel-JSON-XS  perl-Crypt-CBC  perl-Crypt-DES  perl-Crypt-IDEA  perl-Crypt-OpenSSL-Bignum  perl-Crypt-OpenSSL-Guess  perl-Crypt-OpenSSL-RSA  perl-Crypt-OpenSSL-Random  perl-Crypt-PasswdMD5  perl-DBD-MySQL  perl-Data-Munge  perl-Data-Peek  perl-Data-Section  perl-Data-UUID  perl-Date-ISO8601  perl-Date-Manip  perl-DateTime  perl-DateTime-Format-Builder  perl-DateTime-Format-DateParse  perl-DateTime-Format-HTTP  perl-DateTime-Format-IBeat  perl-DateTime-Format-ISO8601  perl-DateTime-Format-Mail  perl-DateTime-Format-Strptime  perl-DateTime-Locale  perl-DateTime-TimeZone  perl-DateTime-TimeZone-SystemV  perl-DateTime-TimeZone-Tzfile  perl-Devel-CallChecker  perl-Devel-EnforceEncapsulation  perl-Devel-Leak  perl-Devel-Size  perl-Digest-BubbleBabble  perl-Digest-CRC  perl-Dist-CheckConflicts  perl-DynaLoader-Functions  perl-EV  perl-Email-Address  perl-Email-Date-Format  perl-Encode-Detect  perl-Encode-EUCJPASCII  perl-Encode-IMAPUTF7  perl-Env-ShellWords  perl-Error  perl-Eval-Closure  perl-Event  perl-Exception-Class  perl-ExtUtils-Config  perl-ExtUtils-Helpers  perl-ExtUtils-InstallPaths  perl-ExtUtils-PkgConfig  perl-FCGI  perl-FFI-CheckLib  perl-File-BOM  perl-File-BaseDir  perl-File-CheckTree  perl-File-Copy-Recursive  perl-File-DesktopEntry  perl-File-Find-Object  perl-File-Find-Object-Rule  perl-File-Find-Rule  perl-File-Find-Rule-Perl  perl-File-Inplace  perl-File-MimeInfo  perl-File-ReadBackwards  perl-File-Remove  perl-File-ShareDir  perl-File-ShareDir-Install  perl-File-Slurp  perl-File-Slurp-Tiny  perl-File-Slurper  perl-File-Type  perl-File-chdir  perl-Font-TTF  perl-FreezeThaw  perl-GD  perl-GD-Barcode  perl-GSSAPI  perl-Getopt-ArgvFile  perl-Graphics-ColorNamesLite-WWW  perl-Guard  perl-HTML-Tree  perl-Hook-LexWrap  perl-IO-AIO  perl-IO-All  perl-IO-CaptureOutput"
echo
echo
echo "Building 901 to 1000 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "perl-IO-Compress-Lzma  perl-IO-Multiplex  perl-IO-SessionData  perl-IO-Socket-INET6  perl-IPC-Run  perl-IPC-Run3  perl-IPC-System-Simple  perl-Image-Base  perl-Image-Info  perl-Image-Xbm  perl-Image-Xpm  perl-Importer  perl-Inline-Files  perl-JSON-Color  perl-JSON-MaybeXS  perl-LDAP  perl-LWP-Protocol-https  perl-Lingua-EN-Inflect  perl-List-MoreUtils-XS  perl-Locale-Codes  perl-Locale-Maketext-Gettext  perl-Locale-Msgfmt  perl-Locale-PO  perl-Log-Message  perl-Log-Message-Simple  perl-MIME-Charset  perl-MIME-Lite  perl-MIME-Types  perl-MLDBM  perl-MRO-Compat  perl-Mail-AuthenticationResults  perl-Mail-DKIM  perl-Mail-IMAPTalk  perl-Mail-SPF  perl-MailTools  perl-Math-Int64  perl-Mixin-Linewise  perl-Module-Build-Tiny  perl-Module-Install-AuthorRequires  perl-Module-Install-AutoLicense  perl-Module-Install-GithubMeta  perl-Module-Install-ManifestSkip  perl-Module-Install-ReadmeFromPod  perl-Module-Install-ReadmeMarkdownFromPod  perl-Module-Install-TestBase  perl-Module-Load-Util  perl-Module-Manifest  perl-Module-Manifest-Skip  perl-Module-Package  perl-Module-Package-Au  perl-Module-Pluggable  perl-Module-Signature  perl-Mojolicious  perl-Moo  perl-Mozilla-CA  perl-Mozilla-LDAP  perl-NNTPClient  perl-Net-CIDR-Lite  perl-Net-DNS  perl-Net-DNS-Resolver-Mock  perl-Net-DNS-Resolver-Programmable  perl-Net-Daemon  perl-Net-IMAP-Simple  perl-Net-IMAP-Simple-SSL  perl-Net-IP  perl-Net-LibIDN2  perl-Net-Patricia  perl-Net-SMTP-SSL  perl-Net-SNMP  perl-Net-Telnet  perl-Newt  perl-Number-Compare  perl-Object-Deadly  perl-Object-HashBase  perl-PAR-Dist  perl-PPI  perl-PPI-HTML  perl-PPIx-QuoteLike  perl-PPIx-Regexp  perl-PPIx-Utilities  perl-Package-Anon  perl-Package-Constants  perl-Package-DeprecationManager  perl-Package-Stash  perl-Package-Stash-XS  perl-Paper-Specs  perl-Parallel-Iterator  perl-Params-Classify  perl-Params-Validate  perl-Params-ValidationCompiler  perl-Parse-RecDescent  perl-Parse-Yapp  perl-Path-Tiny  perl-Perl-Critic  perl-Perl-Critic-More  perl-Perl-MinimumVersion  perl-Perl4-CoreLibs  perl-PerlIO-gzip  perl-PerlIO-utf8_strict  perl-PkgConfig-LibPkgConf"
echo
echo
echo "Building 1001 to 1100 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "perl-Pod-Coverage-TrustPod  perl-Pod-Escapes  perl-Pod-Eventual  perl-Pod-LaTeX  perl-Pod-Markdown  perl-Pod-POM  perl-Pod-Plainer  perl-Pod-Spell  perl-Probe-Perl  perl-Razor-Agent  perl-Readonly  perl-Readonly-XS  perl-Ref-Util  perl-Ref-Util-XS  perl-Regexp-Pattern-Perl  perl-Return-MultiLevel  perl-Role-Tiny  perl-SGMLSpm  perl-SNMP_Session  perl-Scope-Guard  perl-Scope-Upper  perl-Socket6  perl-Software-License  perl-Sort-Versions  perl-Specio  perl-Spiffy  perl-String-CRC32  perl-String-Format  perl-String-Similarity  perl-Sub-Info  perl-Sub-Uplevel  perl-Switch  perl-Syntax-Highlight-Engine-Kate  perl-Sys-CPU  perl-Sys-MemInfo  perl-Taint-Runtime  perl-Task-Weaken  perl-Term-Size-Any  perl-Term-Size-Perl  perl-Term-Table  perl-Term-UI  perl-TermReadKey  perl-Test-Base  perl-Test-CPAN-Meta  perl-Test-CPAN-Meta-JSON  perl-Test-ClassAPI  perl-Test-Differences  perl-Test-DistManifest  perl-Test-Distribution  perl-Test-EOL  perl-Test-Exception  perl-Test-Exit  perl-Test-FailWarnings  perl-Test-File  perl-Test-File-ShareDir  perl-Test-Harness  perl-Test-HasVersion  perl-Test-InDistDir  perl-Test-Inter  perl-Test-LongString  perl-Test-Manifest  perl-Test-MinimumVersion  perl-Test-MockObject  perl-Test-MockRandom  perl-Test-NoTabs  perl-Test-Object  perl-Test-Portability-Files  perl-Test-RequiresInternet  perl-Test-Script  perl-Test-Simple  perl-Test-SubCalls  perl-Test-Synopsis  perl-Test-TrailingSpace  perl-Test-Vars  perl-Test-Warn  perl-Test-utf8  perl-Test2-Plugin-NoWarnings  perl-Test2-Suite  perl-Test2-Tools-Explain  perl-Text-CSV_XS  perl-Text-CharWidth  perl-Text-Diff  perl-Text-Glob  perl-Text-Iconv  perl-Text-Soundex  perl-Text-Unidecode  perl-Text-WrapI18N  perl-Tie-IxHash  perl-Tree-DAG_Node  perl-UNIVERSAL-can  perl-UNIVERSAL-isa  perl-Unicode-EastAsianWidth  perl-Unicode-LineBreak  perl-Unicode-Map8  perl-Unicode-String  perl-Unicode-UTF8  perl-Unix-Syslog  perl-Variable-Magic  perl-Version-Requirements  perl-XML-Catalog"
echo
echo
echo "Building 1101 to 1200 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "perl-XML-DOM  perl-XML-Dumper  perl-XML-Filter-BufferText  perl-XML-Generator  perl-XML-Grove  perl-XML-Handler-YAWriter  perl-XML-LibXSLT  perl-XML-Parser-Lite  perl-XML-RegExp  perl-XML-SAX-Writer  perl-XML-Simple  perl-XML-TokeParser  perl-XML-TreeBuilder  perl-XML-Twig  perl-XML-Writer  perl-XML-XPathEngine  perl-XString  perl-YAML-LibYAML  perl-YAML-PP  perl-YAML-Syck  perl-boolean  perl-gettext  perl-inc-latest  perl-libnet  perl-libxml-perl  perl-namespace-autoclean  perl-namespace-clean  perl-prefork  perltidy  phodav  physfs  pinfo  pipewire  pkcs11-helper  plexus-pom  plotutils  pmdk-convert  pngcrush  pngnq  po4a  podman  polkit-pkla-compat  portreserve  potrace  powertop  ppp  pps-tools  pptp  procmail  proj  ps_mem  psacct  psl-make-dafsa  psutils  ptlib  publicsuffix  publicsuffix-list  pulseaudio  puppet  pyatspi  pykickstart  pylint  pyparted  pyserial  python-CommonMark  python-IPy  python-PyMySQL  python-aiodns  python-aiohttp  python-alsa  python-argcomplete  python-argparse-manpage  python-astroid  python-augeas  python-azure-sdk  python-beautifulsoup4  python-betamax  python-blinker  python-blivet  python-cheetah  python-cmd2  python-colorama  python-configshell  python-cups  python-curio  python-d2to1  python-dbus-client-gen  python-dbus-python-client-gen  python-dbus-signature-pyparsing  python-dbusmock  python-ddt  python-debtcollector  python-dmidecode  python-dns  python-dtopt  python-dulwich  python-enchant  python-entrypoints  python-extras  python-faker"
echo
echo
echo "Building 1201 to 1300 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "python-fasteners  python-fixtures  python-flake8  python-flask  python-fluidity-sm  python-funcsigs  python-genshi  python-gssapi  python-hs-dbus-signature  python-httplib2  python-humanize  python-hwdata  python-inotify  python-into-dbus-python  python-iso8601  python-isodate  python-isort  python-itsdangerous  python-justbases  python-justbytes  python-jwcrypto  python-kdcproxy  python-kerberos  python-kmod  python-lazy-object-proxy  python-ldap  python-lit  python-mccabe  python-memcached  python-mimeparse  python-monotonic  python-msal  python-msrestazure  python-mutagen  python-ntlm-auth  python-oauth2client  python-openstackdocstheme  python-oslo-i18n  python-oslo-sphinx  python-paramiko  python-podman-api  python-productmd  python-pycares  python-pydbus  python-pymongo  python-pyperclip  python-pyrsistent  python-pysocks  python-pytest-flake8  python-pytest-relaxed  python-pytest-runner  python-pytest-subtests  python-pytest-timeout  python-pytoml  python-qrcode  python-rdflib  python-recommonmark  python-redis  python-requests-file  python-requests-ftp  python-requests-kerberos  python-requests-mock  python-requests-toolbelt  python-requests_ntlm  python-rfc3986  python-rpmfluff  python-rtslib  python-s3transfer  python-semantic_version  python-should_dsl  python-simpleline  python-slip  python-sniffio  python-soupsieve  python-sphinx-epytext  python-sphinxcontrib-apidoc  python-sphinxcontrib-httpdomain  python-suds  python-systemd  python-tempita  python-testpath  python-testresources  python-testscenarios  python-testtools  python-toml  python-tornado  python-tox  python-trio  python-uamqp  python-unittest2  python-uritemplate  python-urwid  python-varlink  python-voluptuous  python-waitress  python-webencodings  python-webtest  python-whoosh  python-winrm  python-xmltodict"
echo
echo
echo "Building 1301 to 1400 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "python-yubico  python-zmq  python3-mallard-ducktype  python3-typed_ast  pyusb  pywbem  pyxattr  qhull  qpdf  qperf  qr-code-generator  qt5-qtconnectivity  qt5-qtsensors  qt5-qtserialport  quagga  raptor2  rarian  rasqal  rcs  rdist  re2c  realmd  rear  recode  redland  regexp  relaxngDatatype  resource-agents  rhash  rhino  rhnlib  ripgrep  rp-pppoe  rpmlint  rr  rtkit  ruby-augeas  rubygem-bson  rubygem-coderay  rubygem-deep_merge  rubygem-diff-lcs  rubygem-eventmachine  rubygem-flexmock  rubygem-hocon  rubygem-liquid  rubygem-maruku  rubygem-mongo  rubygem-mysql2  rubygem-pkg-config  rubygem-puppet-resource_api  rubygem-rouge  rubygem-rspec-expectations  rubygem-rspec-mocks  rubygem-rspec-support  rubygem-thor  rubygem-thread_order  rusers  rust-cbindgen  samba  sassist  satyr  sbc  sblim-cim-client2  sblim-cmpi-base  sblim-cmpi-devel  sblim-cmpi-fsvol  sblim-cmpi-network  sblim-cmpi-nfsv3  sblim-cmpi-nfsv4  sblim-cmpi-params  sblim-cmpi-sysfs  sblim-cmpi-syslog  sblim-indication_helper  sblim-sfcCommon  sblim-sfcb  sblim-sfcc  sblim-testsuite  sblim-wbemcli  scl-utils  scotch  screen  sdparm  sendmail  serd  servletapi4  servletapi5  setserial  setup  setuptool  sgpio  shapelib  sip  skkdic  slirp4netns  smc-tools  sombok  sord  sound-theme-freedesktop  soundtouch  sox"
echo
echo
echo "Building 1401 to 1500 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "soxr  sparsehash  spausedd  speex  speexdsp  spice-protocol  spice-vdagent  splix  squid  sratom  star  startup-notification  stress-ng  stunnel  subscription-manager  suitesparse  switcheroo-control  systemd-bootchart  t1lib  t1utils  taglib  tang  targetcli  tbb  tcl-pgtcl  tclx  teckit  telnet  tix  tk  tlog  tmpwatch  tn5250  tofrodos  tpm-tools  trilead-ssh2  tss2  ttmkfdir  twolame  uchardet  ucpp  ucs-miscfixed-fonts  udftools  udica  udisks2  uglify-js  umoci  unicode-emoji  unicode-ucd  unique3  units  upower  uriparser  urlview  usb_modeswitch  usb_modeswitch-data  usbguard  usbmuxd  ustr  uthash  uw-imap  v4l-utils  vhostmd  vino  virt-p2v  virt-top  virt-who  vmem  volume_key  vorbis-tools  watchdog  wavpack  web-assets  webrtc-audio-processing  whois  wireshark  woff2  wordnet  wpebackend-fdo  wsmancli  wvdial  x3270  xalan-j2  xapian-core  xbean  xcb-util-wm  xdelta  xdg-dbus-proxy  xdg-utils  xerces-j2  xfconf  xfsdump  xhtml1-dtds  xmldb-api  xmlrpc-c  xmlunit  xorg-x11-drv-libinput  xorg-x11-fonts  xorg-x11-server  xorg-x11-utils"
echo
echo
echo "Building 1501 to 1513 packages================================"
./pkgbld.sh -r -s ../SPECS-EXTENDED -p "xpp2  xpp3  xrestop  xterm  xz-java  yelp-tools  yelp-xsl  ykclient  ypserv  z3  zenity  zopfli  zziplib"
