#!/bin/bash
#Given an input file which provides list of PR numbers - one PR per line
#this script tells which PRs are approved and which are not approved.
#Since $? is being printed after grep on "approved", a 0 in the second 
#field indicates "Approved" and a 1 in the second field indicates
#"Not Approved". 
#Therefore, results are in the following form
#If PRNUM1 is Approved and PRNUM2 is Not Approved, the output of this
#script will be 
#PRNUM1,0
#PRNUM2,1


PRLST_FL=$1

for prnum in `cat $PRLST_FL`
do
echo -n "$prnum,"
gh pr view $prnum --comments -R https://github.com/microsoft/azurelinux.git | grep -e "status:[[:space:]]approved" > /dev/null
echo "$?"
done
